form-flow:
  email-client:
    mailgun:
      key: ${MAILGUN_KEY:'no-key-set'}
      domain: 'mg.marylandbenefits.org'
      sender-email: 'Maryland Benefits STAGING <help@marylandbenefits.org>'
spring:
  thymeleaf:
    cache: true
  session:
    jdbc:
      initialize-schema: always
management:
  endpoints:
    enabled-by-default: false