form-flow:
  lock-after-submitted:
    - flow: mdBenefitsFlow
      redirect: confirmation
  disabled-flows: ~
  pdf:
    path: 'src/main/resources/pdfs/'
    map-file: pdf-map.yaml
  inputs: 'org.mdbenefits.app.inputs.'
  path: 'flows-config.yaml'
  uploads:
    default-doc-type-label: "NotSet"
    accepted-file-types: '.jpg,.jpeg,.png,.doc,.docx,.pdf,.xls,.xlsx,.ppt,.pptx,.txt,.csv'
    thumbnail-width: '64'
    thumbnail-height: '60'
    # 20 files maximum
    max-files: '20'
    # file size limit in MB
    # If this is not set then the server values below for servlet max-file-size and tomcat max POST size will not be set
    # which will cause the server to use the default values of 1MB preventing uploads larger than that.
    max-file-size: '20'
  mixpanel:
    api-key: ${MIXPANEL_API_KEY}
  aws:
    region: 'us-east-1'
    s3_bucket_name: ${AWS_BUCKET}
    access_key: ${AWS_ACCESS_KEY}
    secret_key: ${AWS_SECRET_KEY}
    cmk: ${AWS_CMK}
  address-validation:
    smarty:
      auth-id: ${SMARTY_AUTH_ID}
      auth-token: ${SMARTY_AUTH_TOKEN}
  email-client:
    mailgun:
      key: ${MAILGUN_KEY:'no-key-set'}
      domain: 'mg.marylandbenefits.org'
      sender-email: 'Maryland Benefits DEMO <help@marylandbenefits.org>'
spring:
  flyway:
    placeholders:
      uuid_function: "gen_random_uuid"
      user_file_doc_type_default_label: ${form-flow.uploads.default-doc-type-label:#{null}}
  profiles:
    group:
      test:
        - test
        - form-flow-library-test
      dev:
        - dev
        - form-flow-library
      demo:
        - demo
        - form-flow-library
      staging:
        - staging
        - form-flow-library
      prod:
        - prod
        - form-flow-library
  thymeleaf:
    cache: false
    template-resolver-order: 0
    check-template-location: true
  # TODO: move caching 0 to a dev only context?
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
        cachecontrol:
          max-age: 7d
    locale: ${DEFAULT_LOCALE}
    locale-resolver: fixed
  datasource:
    url: jdbc:postgresql://localhost:5432/mdbenefits
  servlet:
    multipart:
      max-file-size: ${form-flow.uploads.max-file-size}MB
      max-request-size: ${form-flow.uploads.max-file-size}MB
logging:
  level:
    root: INFO
    org:
      springframework:
        boot:
          autoconfigure:
            security:
              servlet:
                UserDetailsServiceAutoConfiguration: OFF
server:
  tomcat:
    max-http-form-post-size: ${form-flow.uploads.max-file-size}MB
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
  servlet:
    session:
      persistent: true
management:
  endpoints:
    enabled-by-default: false
transmission:
  transmission-initial-delay-seconds: 60
  transmission-rate-seconds: 300
  email-recipients:
    baltimore-county: ${BALTIMORE_COUNTY_EMAIL_ADDRESSES}
    queen-annes-county: ${QUEENANNES_COUNTY_EMAIL_ADDRESSES}
  google-drive-directory-id:
    baltimore-county: ${BALTIMORE_COUNTY_GOOGLE_DIR_ID}
    queen-annes-county: ${QUEENANNES_COUNTY_GOOGLE_DIR_ID}
