spring:
  thymeleaf:
    cache: true
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/mdbenefits
form-flow:
  disabled-flows: ~
  uploads:
    max-file-size: '5'
    default-doc-type-label: "NotSet"
