form-flow:
  session-continuity-interceptor:
    enabled: false
  disabled-flows: ~
  uploads:
    default-doc-type: "NotSet"
    accepted-file-types: '.jpeg,.jpg,.png,.pdf,.bmp,.gif,.doc,.docx,.odt,.ods,.odp'
    thumbnail-width: '54'
    thumbnail-height: '50'
    max-files: '5' # 5 files maximum
    max-file-size: '1' # 1 MB file size limit
  address-validation:
    disabled: true
    smarty:
      auth-id: 'test-id'
      auth-token: 'test-token'
spring:
  messages:
    basename: messages, messages-form-flow
  datasource:
    url: jdbc:postgresql://localhost:5432/mdbenefits_test
    username: mdbenefits_test
    password: postgres
  flyway:
    baselineOnMigrate: true
    clean-on-validation-error: true
    placeholders:
      uuid_function: "gen_random_uuid"
      user_file_doc_type_default_label: ${form-flow.uploads.default-doc-type-label:#{null}}
    clean-disabled: false
  thymeleaf:
    prefix: classpath:/templates/
  main:
    allow-circular-references: true
  session:
    store-type: jdbc
    timeout: 72h
    jdbc:
      initialize-schema: always
transmission:
  # keep these large so transmissions do not run during testing
  transmission-rate-seconds: 10000
  transmission-initial-delay-seconds: 10000
  email-recipients:
    baltimore-county: test@maininator.com
    queen-annes-county: test@mailinator.com
  google-drive-directory-id:
    baltimore-county: 12345
    queen-annes-county: 23456
