form-flow:
  disabled-flows: ~
spring:
  flyway:
    baseline-on-migrate: true
sftp:
  environment-path: 'staging'
google:
  drive:
    baltimore-county-directory-id: ${BALTIMORE_COUNTY_GOOGLE_DIR_ID_STAGING}
    queen-annes-county-directory-id: ${QUEENANNES_COUNTY_GOOGLE_DIR_ID_STAGING}