name: mdBenefitsFlow
flow:
  county:
    nextScreens:
      - name: redirectToMDThink
        condition: ShouldRedirectToMDThink
      - name: selectApplication
  selectApplication:
    nextScreens:
      - name: redirectToMDThink
        condition: ShouldRedirectToMDThink
      - name: selectHelpNeeded
  # this page is offboarding them
  redirectToMDThink:
    nextScreens:
      - name: redirectToMDThink
  selectHelpNeeded:
    beforeSaveAction: PreCheckPrograms
    nextScreens:
      - name: choosePrograms
  choosePrograms:
    nextScreens:
      # we are not doing expeditedSnap during the first phase, but leaving this in
      # for v1.5 phase
      #      - name: expeditedSnapNotice
      #  expeditedSnapNotice:
      #    condition: ProgramsIncludeSnap
      #    nextScreens:
      - name: ohepNotice
  ohepNotice:
    condition: ProgramsIncludeSnapOrTCA
    nextScreens:
      - name: howThisWorks
  howThisWorks:
    nextScreens:
      - name: signPost
  signPost:
    nextScreens:
      - name: personalInfo
  personalInfo:
    crossFieldValidationAction: ValidateBirthdate
    nextScreens:
      - name: homeAddress
  homeAddress:
    crossFieldValidationAction: ValidateHomeAddress
    onPostAction: ClearNoHomeAddressIfNotSelected
    nextScreens:
      - name: mailingAddress
  mailingAddress:
    crossFieldValidationAction: ValidateMailingAddress
    onPostAction: ClearSameAsHomeAddressIfNotSelected
    nextScreens:
      - name: selectAddress
        condition: SmartySuggestionFound
      - name: verifyAddress
        condition: SmartySuggestionNotFound
      - name: contactInfo
  verifyAddress:
    nextScreens:
      - name: contactInfo
  selectAddress:
    nextScreens:
      - name: contactInfo
  contactInfo:
    crossFieldValidationAction: ValidateContactMethod
    nextScreens:
      - name: contactInfoNudge
        condition: ContactInfoMissing
      - name: contactInfoReview
  contactInfoNudge:
    nextScreens:
      - name: contactInfoReview
  contactInfoReview:
    nextScreens:
      - name: householdSignPost
  expeditedSnapStart:
    nextScreens:
      - name: finalSignPost
        condition: IsMinimumApplication
      - name: householdHasAdditionalMembers
  householdIncomeLast30Days:
    nextScreens:
      - name: expeditedMoneyOnHandAmount
  expeditedMoneyOnHandAmount:
    nextScreens:
      - name: householdRent
  householdRent:
    nextScreens:
      - name: householdRentAmount
  householdRentAmount:
    nextScreens:
      - name: householdSignPost
  householdSignPost:
    nextScreens:
      - name: applicantApplying
  applicantApplying:
    nextScreens:
      - name: applicantSex
        condition: IsApplicantApplyingForSelf
      - name: householdHasAdditionalMembers
  # Not a next screen of any screen but directly linked to from applicantApplying
  whyWeAskForSSN:
    nextScreens:
      - name: null
  applicantSex:
    nextScreens:
      - name: applicantPregnancy
        condition: DisplayPregnancyQuestion
      - name: applicantSchoolInfo
  applicantPregnancy:
    nextScreens:
      - name: applicantSchoolInfo
  applicantSchoolInfo:
    nextScreens:
      - name: applicantDisability
  applicantDisability:
    nextScreens:
      - name: applicantRace
  applicantRace:
    nextScreens:
      - name: householdHasAdditionalMembers
  householdHasAdditionalMembers:
    nextScreens:
      - name: householdList
        condition: HasHousehold
      - name: householdSeasonalFarmWorker

  ## END applicant information

  householdList:
    nextScreens:
      - name: householdSeasonalFarmWorker
  householdInfo:
    subflow: household
    nextScreens:
      - name: householdAdditionalInfo
        condition: IsHouseholdMemberApplying
      - name: householdList
  householdAdditionalInfo:
    crossFieldValidationAction: ValidateHouseholdBirthdate
    subflow: household
    nextScreens:
      - name: householdRaceAndEthnicity
  householdRaceAndEthnicity:
    subflow: household
    nextScreens:
      - name: householdList
  householdMemberDeleteConfirmation:
    nextScreens: null
  householdSpecialSituations:
    nextScreens:
      - name: householdSeasonalFarmWorker
  householdSeasonalFarmWorker:
    beforeSaveAction: CheckExpeditedSnapEligibility
    nextScreens:
      - name: incomeSignPost
        condition: IsNotApplyingForExpeditedSnap
      - name: expeditedSnapQualificationNotice
        condition: IsEligibleForExpeditedSnap
      - name: expeditedSnapDeferredNotice
  expeditedSnapQualificationNotice:
    nextScreens:
      - name: finalSignPost
  expeditedSnapDeferredNotice:
    nextScreens:
      - name: finalSignPost
  incomeSignPost:
    nextScreens:
      - name: incomeLessThan150
  incomeLessThan150:
    nextScreens:
      - name: householdIncome
  householdIncome:
    nextScreens:
      - name: householdIncomeByJob
        condition: HasIncome
      - name: householdAdditionalIncome
  householdIncomeByJob:
    nextScreens:
      - name: householdIncomeWho
  householdIncomeWho:
    subflow: income
    nextScreens:
      - name: householdEmployerName
  householdIncomeDeleteConfirmation:
    nextScreens: null
  householdEmployerName:
    subflow: income
    nextScreens:
      - name: jobPaidByHour
  jobPaidByHour:
    subflow: income
    nextScreens:
      - name: jobHourlyWage
        condition: JobPaidByTheHour
      - name: jobPayPeriod
  jobHourlyWage:
    subflow: income
    nextScreens:
      - name: jobHoursPerWeek
  jobHoursPerWeek:
    subflow: income
    nextScreens:
      - name: householdIncomeList
  jobPayPeriod:
    subflow: income
    nextScreens:
      - name: jobPayAmount
  jobPayAmount:
    subflow: income
    nextScreens:
      - name: householdIncomeList
  householdIncomeList:
    nextScreens:
      - name: householdAdditionalIncome
  householdAdditionalIncome:
    beforeSaveAction: ClearUnusedAdditionalIncomeFields
    nextScreens:
      - name: householdAdditionalIncomeAmount
        condition: HasAdditionalIncome
      - name: householdMoneyOnHand
  householdAdditionalIncomeAmount:
    nextScreens:
      - name: householdMoneyOnHand
  householdMoneyOnHand:
    nextScreens:
      - name: expensesSignPost
  expensesSignPost:
    nextScreens:
      - name: householdHomeExpenses
  householdHomeExpenses:
    beforeSaveAction: ClearUnusedExpensesFields
    nextScreens:
      - name: householdHomeExpensesAmount
        condition: HasHouseholdHomeExpenses
      - name: ohepRent
        condition: HasHouseholdRentExpenses
      - name: ohepElectricity
  householdHomeExpensesAmount:
    nextScreens:
      - name: ohepRent
        condition: HasHouseholdRentExpenses
      - name: ohepElectricity
  ohepRent:
    nextScreens:
      - name: ohepElectricity
  ohepElectricity:
    nextScreens:
      - name: ohepHeating
  ohepHeating:
    nextScreens:
      - name: householdMedicalExpenses
        condition: HasHouseholdMemberOver60
      - name: expensesDependentCare
  householdMedicalExpenses:
    nextScreens:
      - name: householdMedicalExpensesAmount
        condition: HasMedicalExpenses
      - name: expensesDependentCare
  householdMedicalExpensesAmount:
    nextScreens:
      - name: expensesDependentCare
  expensesDependentCare:
    nextScreens:
      - name: expensesDependentCareAmount
        condition: HasDependentCareExpenses
      - name: expensesChildSupport
  expensesDependentCareAmount:
    nextScreens:
      - name: expensesChildSupport
  expensesChildSupport:
    nextScreens:
      - name: expensesChildSupportAmount
        condition: HasChildSupportExpenses
      - name: docUploadIntro
  expensesChildSupportAmount:
    nextScreens:
      - name: finalSignPost
  finalSignPost:
    nextScreens:
      - name: registerToVote
  registerToVote:
    nextScreens:
      - name: docUploadIntro
  docUploadIntro:
    nextScreens:
      - name: legalStuff
        condition: DoesNotWantToAddDocs
      - name: docUploadInstructions
  docUploadInstructions:
    nextScreens:
      - name: signature
        condition: DoesNotWantToAddDocs
      - name: docUpload
  docUpload:
    nextScreens:
      - name: docUploadFinish
  docUploadFinish:
    nextScreens:
      - name: legalStuff
  legalStuff:
    nextScreens:
      - name: sensitiveConvictionQuestionsIntro
  sensitiveConvictionQuestionsIntro:
    nextScreens:
      - name: sensitiveConvictionQuestions
  sensitiveConvictionQuestions:
    beforeDisplayAction: SetDefaultSensitiveConvictionAnswers
    nextScreens:
      - name: rightsAndResponsibilities
  rightsAndResponsibilities:
    nextScreens:
      - name: tcaOhepAgreement
  tcaOhepAgreement:
    nextScreens:
      - name: signature
  signature:
    afterSaveAction: HandleApplicationSigned
    nextScreens:
      - name: confirmation
  confirmation:
    beforeDisplayAction: FormatSubmittedAtDate
    nextScreens:
      - name: confirmation
landmarks:
  firstScreen: county
  afterSubmitPages:
    - confirmation
subflows:
  household:
    entryScreen: householdHasAdditionalMembers
    iterationStartScreen: householdInfo
    reviewScreen: householdList
    deleteConfirmationScreen: householdMemberDeleteConfirmation
  income:
    entryScreen: householdIncomeByJob
    iterationStartScreen: householdIncomeWho
    reviewScreen: householdIncomeList
    deleteConfirmationScreen: householdIncomeDeleteConfirmation
