name: mdBenefitsFlow
flow:
  county:
    nextScreens:
      - name: redirectToMDThink
        condition: ShouldRedirectToMDThink
      - name: selectApplication
  selectApplication:
    nextScreens:
      - name: redirectToMDThink
        condition: ShouldRedirectToMDThink
      - name: selectHelpNeeded
  # this page is offboarding them
  redirectToMDThink:
    nextScreens:
      - name: redirectToMDThink
  selectHelpNeeded:
    nextScreens:
      - name: choosePrograms
  choosePrograms:
    nextScreens:
      - name: signPost
  signPost:
    nextScreens:
      - name: personalInfo
  personalInfo:
    crossFieldValidationAction: ValidateBirthdate
    nextScreens:
      - name: homeAddress
  homeAddress:
    crossFieldValidationAction: ValidateHomeAddress
    onPostAction: ClearNoHomeAddressIfNotSelected
    nextScreens:
      - name: noPermanentAddress
        condition: NoPermanentAddress
      - name: mailingAddress
  noPermanentAddress:
    nextScreens:
      - name: contactInfo
  mailingAddressNoAddress:
    crossFieldValidationAction: ValidateMailingAddress
    nextScreens:
      - name: selectAddress
        condition: SmartySuggestionFound
      - name: verifyAddress
        condition: SmartySuggestionNotFound
      - name: contactInfo
  mailingAddress:
    crossFieldValidationAction: ValidateMailingAddress
    onPostAction: ClearSameAsHomeAddressIfNotSelected
    nextScreens:
      - name: selectAddress
        condition: SmartySuggestionFound
      - name: verifyAddress
        condition: SmartySuggestionNotFound
      - name: contactInfo
  verifyAddress:
    nextScreens:
      - name: contactInfo
  selectAddress:
    nextScreens:
      - name: contactInfo
  contactInfo:
    crossFieldValidationAction: ValidateContactMethod
    nextScreens:
      - name: phoneNumberNudge
        condition: PhoneNumberMissing
      - name: reviewContactInfo
  phoneNumberNudge:
    nextScreens:
      - name: reviewContactInfo
  reviewContactInfo:
    nextScreens:
      - name: multiplePersonHousehold
  expeditedSnapStart:
    nextScreens:
      - name: finalSignPost
        condition: IsMinimumApplication
      - name: multiplePersonHousehold
  multiplePersonHousehold:
    nextScreens:
      - name: householdIncomeLast30Days
        condition: IsApplyingForExpeditedSnap
      - name: householdSignPost
        condition: IsMultiplePersonHousehold
      - name: ssnForm
  householdIncomeLast30Days:
    nextScreens:
      - name: expeditedMoneyOnHandAmount
  expeditedMoneyOnHandAmount:
    nextScreens:
      - name: householdRent
  householdRent:
    nextScreens:
      - name: householdRentAmount
        condition: HouseholdPaysRent
      - name: householdUtilities
  householdRentAmount:
    nextScreens:
      - name: householdUtilities
  householdSignPost:
    nextScreens:
      - name: householdInfo
  householdInfo:
    crossFieldValidationAction: ValidateHouseholdBirthdate
    subflow: household
    nextScreens:
      - name: householdList
  householdList:
    nextScreens:
      - name: ssnForm
        condition: ProgramsIncludeSnap
      - name: householdSpecialSituations
  householdMemberDeleteConfirmation:
    nextScreens: null
  ssnForm:
    beforeSaveAction: EncryptSSNBeforeSaving
    beforeDisplayAction: DecryptSSNBeforeDisplaying
    nextScreens:
      - name: householdSpecialSituations
  ssnFaq:
    nextScreens:
      - name: householdSpecialSituations
  householdSpecialSituations:
    nextScreens:
      - name: householdSchool
  householdSchool:
    nextScreens:
      - name: householdSchoolWho
        condition: GoingToSchool
      - name: householdPregnancy
  householdSchoolWho:
    nextScreens:
      - name: householdSchoolDetails
  householdSchoolDetails:
    beforeDisplayAction: ReformatStudentsUserData
    nextScreens:
      - name: householdPregnancy
  householdPregnancy:
    nextScreens:
      - name: householdPregnancyWho
        condition: IsPregnant
      - name: householdBenefits
  householdPregnancyWho:
    nextScreens:
      - name: householdPregnancyDueDate
  householdPregnancyDueDate:
    beforeDisplayAction: ReformatPregnancyUserData
    nextScreens:
      - name: householdBenefits
  householdBenefits:
    nextScreens:
      - name: householdBenefitsWho
        condition: OutOfStateBenefits
      - name: householdPrepareFood
        condition: ProgramsIncludeSnap
      - name: sensitiveQuestions
  householdBenefitsWho:
    nextScreens:
      - name: householdPrepareFood
        condition: ProgramsIncludeSnap
      - name: sensitiveQuestions
  householdPrepareFood:
    nextScreens:
      - name: householdSeasonalFarmWorker
        condition: PreparesFoodTogether
      - name: householdPrepareFoodWho
  householdPrepareFoodWho:
    nextScreens:
      - name: householdSeasonalFarmWorker
  householdSeasonalFarmWorker:
    beforeSaveAction: CheckExpeditedSnapEligibility
    nextScreens:
      - name: citizenshipIntro
        condition: IsNotApplyingForExpeditedSnap
      - name: expeditedSnapQualificationNotice
        condition: IsEligibleForExpeditedSnap
      - name: expeditedSnapDeferredNotice
  expeditedSnapQualificationNotice:
    nextScreens:
      - name: finalSignPost
  expeditedSnapDeferredNotice:
    nextScreens:
      - name: finalSignPost
  citizenshipIntro:
    nextScreens:
      - name: citizenshipQuestion
  citizenshipQuestion:
    nextScreens:
      - name: householdVeteran
        condition: AllUSCitizens
      - name: citizenshipSelectStatus
  citizenshipSelectStatus:
    beforeSaveAction: MoveCitizenshipData
    nextScreens:
      - name: householdVeteran
  householdVeteran:
    nextScreens:
      - name: householdVeteranWho
        condition: IsVeteran
      - name: householdFoster
  householdVeteranWho:
    nextScreens:
      - name: householdFoster
  householdFoster:
    nextScreens:
      - name: householdFosterWho
        condition: IsFosterPerson
      - name: householdFosterAgedOut
  householdFosterWho:
    nextScreens:
      - name: householdFosterAgedOut
  householdFosterAgedOut:
    nextScreens:
      - name: householdFosterAgedOutWho
        condition: FostersAgedOut
      - name: householdHomeless
  householdFosterAgedOutWho:
    nextScreens:
      - name: householdHomeless
  householdHomeless:
    nextScreens:
      - name: householdHomelessnessWho
        condition: IsHomeless
      - name: householdRoomRental
  householdHomelessnessWho:
    nextScreens:
      - name: householdRoomRental
  householdRoomRental:
    nextScreens:
      - name: householdRoomRentalWho
        condition: HasRoomRental
      - name: householdMeals
  householdRoomRentalWho:
    nextScreens:
      - name: householdMeals
  householdMeals:
    nextScreens:
      - name: householdMealsWho
        condition: PayForMeals
      - name: sensitiveQuestions
  householdMealsWho:
    nextScreens:
      - name: sensitiveQuestions
  sensitiveQuestions:
    nextScreens:
      - name: householdPersonalSituations
  householdPersonalSituations:
    nextScreens:
      - name: householdPersonalSituationsWho
        condition: HouseholdHasPersonalSituations
      - name: householdVictimOfDomesticViolence
  householdPersonalSituationsWho:
    beforeSaveAction: ReformatPersonalSituationUserData
    nextScreens:
      - name: householdWhichPersonalSituations
  householdWhichPersonalSituations:
    nextScreens:
      - name: householdVictimOfDomesticViolence
  householdVictimOfDomesticViolence:
    nextScreens:
      - name: householdSensitiveQuestionsCriminalJustice
  householdSensitiveQuestionsCriminalJustice:
    nextScreens:
      - name: householdCriminalJusticeSituations
  householdCriminalJusticeSituations:
    nextScreens:
      - name: incomeSignPost
  incomeSignPost:
    nextScreens:
      - name: householdJobSearch
  householdJobSearch:
    nextScreens:
      - name: householdJobSearchWho
        condition: HouseholdJobSearch
      - name: householdWorkDisqualifications
  householdJobSearchWho:
    nextScreens:
      - name: householdWorkDisqualifications
  householdWorkDisqualifications:
    nextScreens:
      - name: householdEmploymentStatus
  householdEmploymentStatus:
    nextScreens:
      - name: householdIncomeByJob
  householdIncomeByJob:
    nextScreens:
      - name: householdIncomeWho
  householdIncomeWho:
    subflow: income
    nextScreens:
      - name: householdEmployerName
  householdIncomeDeleteConfirmation:
    nextScreens: null
  householdEmployerName:
    subflow: income
    nextScreens:
      - name: householdSelfEmployment
  householdSelfEmployment:
    subflow: income
    nextScreens:
      - name: jobPaidByHour
  jobPaidByHour:
    subflow: income
    nextScreens:
      - name: jobHourlyWage
        condition: JobPaidByTheHour
      - name: jobPayPeriod
  jobHourlyWage:
    subflow: income
    nextScreens:
      - name: jobHoursPerWeek
  jobHoursPerWeek:
    subflow: income
    nextScreens:
      - name: householdIncomeConfirmation
  jobPayPeriod:
    subflow: income
    nextScreens:
      - name: jobPayAmount
  jobPayAmount:
    subflow: income
    nextScreens:
      - name: householdIncomeConfirmation
  householdIncomeConfirmation:
    nextScreens:
      - name: householdIncomeList
  householdIncomeList:
    nextScreens:
      - name: householdAdditionalIncome
  householdAdditionalIncome:
    nextScreens:
      - name: householdMoneyOnHand
        condition: ProgramsIncludeSnap
      - name: expensesSignPost
  householdMoneyOnHand:
    nextScreens:
      - name: householdMoneyOnHandDetails
        condition: HasMoneyOnHand
      - name: expensesSignPost
  householdMoneyOnHandDetails:
    nextScreens:
      - name: householdRent
        condition: IsApplyingForExpeditedSnap
      - name: expensesSignPost
  expensesSignPost:
    nextScreens:
      - name: householdHomeExpenses
  householdHomeExpenses:
    nextScreens:
      - name: householdHomeExpensesAmount
        condition: HasHouseholdHomeExpenses
      - name: householdUtilities
  householdHomeExpensesAmount:
    nextScreens:
      - name: householdUtilities
  householdUtilities:
    nextScreens:
      - name: householdSeasonalFarmWorker
        condition: IsApplyingForExpeditedSnapAndHasNoUtilityExpenses
      - name: householdUtilitiesAmount
        condition: HasUtilitiesExpenses
      - name: energyAssistance
  householdUtilitiesAmount:
    nextScreens:
      - name: householdSeasonalFarmWorker
        condition: IsApplyingForExpeditedSnap
      - name: energyAssistance
  energyAssistance:
    nextScreens:
      - name: liheap
        condition: ReceivesEnergyAssistance
      - name: householdMedicalExpenses
  liheap:
    nextScreens:
      - name: householdMedicalExpenses
  householdMedicalExpenses:
    nextScreens:
      - name: householdMedicalExpensesAmount
        condition: HasMedicalExpenses
      - name: expensesDependentCare
  householdMedicalExpensesAmount:
    nextScreens:
      - name: expensesDependentCare
  expensesDependentCare:
    nextScreens:
      - name: expensesDependentCareAmount
        condition: HasDependentCareExpenses
      - name: expensesChildSupport
  expensesDependentCareAmount:
    nextScreens:
      - name: expensesChildSupport
  expensesChildSupport:
    nextScreens:
      - name: expensesChildSupportAmount
        condition: HasChildSupportExpenses
      - name: expensesElderlyCare
  expensesChildSupportAmount:
    nextScreens:
      - name: expensesElderlyCare
  expensesElderlyCare:
    nextScreens:
      - name: expensesElderlyCareAmount
        condition: HasElderlyCareExpenses
      - name: finalSignPost
  expensesElderlyCareAmount:
    nextScreens:
      - name: finalSignPost
  finalSignPost:
    nextScreens:
      - name: ebtCard
  ebtCard:
    nextScreens:
      - name: registerToVote
  registerToVote:
    nextScreens:
      - name: raceEthnicityAsk
  raceEthnicityAsk:
    nextScreens:
      - name: ethnicitySelection
        condition: ApplicantRaceEthnicityQuestionsAllowed
      - name: docUploadIntro
  ethnicitySelection:
    nextScreens:
      - name: raceSelection
  raceSelection:
    nextScreens:
      - name: docUploadIntro
  docUploadIntro:
    nextScreens:
      - name: legalStuff
        condition: DoesNotWantToAddDocs
      - name: docUploadInstructions
  docUploadInstructions:
    nextScreens:
      - name: signature
        condition: DoesNotWantToAddDocs
      - name: docUpload
  docUpload:
    nextScreens:
      - name: docUploadFinish
  docUploadFinish:
    nextScreens:
      - name: legalStuff
  legalStuff:
    nextScreens:
      - name: sensitiveConvictionQuestionsIntro
  sensitiveConvictionQuestionsIntro:
    nextScreens:
      - name: sensitiveConvictionQuestions
  sensitiveConvictionQuestions:
    beforeDisplayAction: SetDefaultSensitiveConvictionAnswers
    nextScreens:
      - name: rightsAndResponsibilities
  rightsAndResponsibilities:
    nextScreens:
      - name: tcaOhepAgreement
  tcaOhepAgreement:
    nextScreens:
      - name: signature
  signature:
    afterSaveAction: HandleApplicationSigned
    nextScreens:
      - name: confirmation
  confirmation:
    beforeDisplayAction: FormatSubmittedAtDate
    nextScreens:
      - name: confirmation
landmarks:
  firstScreen: county
  afterSubmitPages:
    - confirmation
subflows:
  household:
    entryScreen: multiplePersonHousehold
    iterationStartScreen: householdInfo
    reviewScreen: householdList
    deleteConfirmationScreen: householdMemberDeleteConfirmation
  income:
    entryScreen: householdIncomeByJob
    iterationStartScreen: householdIncomeWho
    reviewScreen: householdIncomeList
    deleteConfirmationScreen: householdIncomeDeleteConfirmation
