name: Deploy to Aptible Staging

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs: { }

jobs:
  deploy:
    name: Deploy to aptible-staging
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.APTIBLE_GIT_SSH_KEY }}
      - name: Deploy Using Aptible CLI
        run: |
          ssh-keyscan beta.aptible.com >> ~/.ssh/known_hosts
          wget -O aptible-package https://omnibus-aptible-toolbelt.s3.amazonaws.com/aptible/omnibus-aptible-toolbelt/master/206/pkg/aptible-toolbelt_0.16.5%2B20200508143656~ubuntu.16.04-1_amd64.deb
          sudo dpkg -i aptible-package
          aptible login \
            --email='${{ secrets.APTIBLE_USERNAME }}' \
            --password='${{ secrets.APTIBLE_PASSWORD}}'      
          git push --force ${{ vars.APTIBLE_REMOTE_URL }} ${GITHUB_SHA}:${{ vars.APTIBLE_REMOTE_BRANCH }}
          aptible deploy \
            --app sn-md-pilot-staging \
            --git-commitish ${GITHUB_SHA} \
            'SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}' \
            'SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}' \
            'SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}' \
            'AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}' \
            'AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}' \
            'AWS_BUCKET=${{ vars.AWS_BUCKET }}' \
            'MAILGUN_KEY=${{ secrets.MAILGUN_KEY }}' \
            'SPRING_PROFILES_ACTIVE=staging' \
            'ENCRYPTION_KEYSET=${{ secrets.ENCRYPTION_KEYSET }}' \
            'DEFAULT_LOCALE=en' \
            'AWS_CMK=${{ secrets.AWS_CMK }}' \
            'demo=true' \
            'FORCE_SSL=true'
